export const banners = [
  {
    id: 1,
    url: "https://cdn.galaxycine.vn/media/2024/5/24/2048_1716569284149.jpg",
    title: "Banner 1",
    description: "This is the first banner",
  },
  {
    id: 2,
    url: "https://cdn.galaxycine.vn/media/2024/6/3/pht-2048_1717403979854.jpg",
    title: "Banner 2",
    description: "This is the second banner",
  },
  {
    id: 3,
    url: "https://cdn.galaxycine.vn/media/2024/2/8/2048x682_1707364876796.jpg",
    title: "Banner 3",
    description: "This is the third banner",
  },
];
export const selectFilm = [
  "Lật mặt 7",
  "Cái giá của hạnh phúc là 50k",
  "Ngôi đền kỳ quái",
  "Phim ma Phim Hài Phim Hành động Phim kaka",
  "Phim ma Phim Hài Phim Hành động Phim kaka 1",
  "Phim ma Phim Hài Phim Hành động Phim kaka2",
  "Phim ma Phim Hài Phim Hành động Phim kaka3",
  "Phim ma Phim Hài Phim Hành động Phim kaka4",
  "Phim ma Phim Hài Phim Hành động Phim kaka5",
];
export const selectDate = [
  "Thứ Ba, 03/06/2024",
  "Thứ Tư, 04/06/2024",
  "Thứ Năm, 05/06/2024",
];
export const selectTime = ["16:30", "16:31", "16:32"];
export const films = [
  {
    id: 1,
    url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-1_1716798361490.jpg",
    banner:
      "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
    title: "Mèo béo siêu quậy",
    slug: "meo-beo-sieu-quay",
    movieSchedule: ["06/06/2024", "07/06/2024", "08/06/2024"],
    actors: [
      {
        name: "Pavel Priluchniy",
        url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
      },
      {
        name: "Polina Gagarina",
        url: "https://cdn.galaxycine.vn/media/2019/4/10/avengers5_1554870743667.jpg",
      },
      {
        name: "Roman Kurtsyn",
        url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
      },
      {
        name: "Roman Kurtsyn",
        url: "https://cdn.galaxycine.vn/media/2019/4/10/avengers5_1554870743667.jpg",
      },
      {
        name: "Roman Kurtsyn",
        url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
      },
      {
        name: "Roman Kurtsyn",
        url: "https://cdn.galaxycine.vn/media/2019/4/10/avengers5_1554870743667.jpg",
      },
      {
        name: "Roman Kurtsyn",
        url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
      },
      {
        name: "Roman Kurtsyn",
        url: "https://cdn.galaxycine.vn/media/2019/4/10/avengers5_1554870743667.jpg",
      },
      {
        name: "Roman Kurtsyn",
        url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
      },
      {
        name: "Roman Kurtsyn",
        url: "https://cdn.galaxycine.vn/media/2019/4/10/avengers5_1554870743667.jpg",
      },
    ],
    producer: ["Columbia Pictures", "Alcon Entertainment DNEG Animation"],
    category: ["Hài", "Hoạt Hình", "Phiêu Lưu", "Live Action"],
    director: ["Mark Dindal"],
    nation: "Mỹ",
    content: [
      'Đang tận hưởng cuộc sống vương giả, được cưng nựng, nuông chiều như vua chúa cùng "con sen" Jon. Thế nhưng, chẳng ai ngờ, một đêm nọ, kiếp nạn tìm tới khi Garfield và Odie bị một băng mèo hoang bắt cóc. Bất ngờ thay, người giải cứu cả hai không ai khác chính là Vic - người bố thất lạc đã lâu của Garfield.',
      "Họa vô đơn chí, Vic lại vướng vào rắc rối với đám mèo hoang. Thế là Garfield và Odie lại bị cuốn vào một phi vụ mới, thay vì về nhà và hưởng thụ kiếp sống của boss.",
    ],
  },
  {
    id: 2,
    url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-1_1716798361490.jpg",
    banner:
      "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
    title: "Mèo béo siêu quậy 1",
    slug: "meo-beo-sieu-quay-1",
    movieSchedule: ["06/06/2024", "06/07/2024", "06/08/2024"],
  },
  {
    id: 3,
    url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-1_1716798361490.jpg",
    banner:
      "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
    title: "Mèo béo siêu quậy 2",
    movieSchedule: ["06/06/2024", "07/06/2024", "06/08/2024"],
    slug: "meo-beo-sieu-quay-2",
  },
  {
    id: 4,
    url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-1_1716798361490.jpg",
    banner:
      "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
    title: "Mèo béo siêu quậy 3",
    movieSchedule: ["06/06/2024", "07/06/2024", "08/06/2024"],

    slug: "meo-beo-sieu-quay-4",
  },
  {
    id: 5,
    url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-1_1716798361490.jpg",
    banner:
      "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
    title: "Mèo béo siêu quậy 5",
    slug: "meo-beo-sieu-quayv5",
    movieSchedule: ["06/06/2024", "07/06/2024", "08/06/2024"],
  },
  {
    id: 6,
    url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-1_1716798361490.jpg",
    banner:
      "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
    title: "Mèo béo siêu quậy 6",
    slug: "meo-beo-sieu-quay-6",
    movieSchedule: ["06/06/2024", "06/07/2024", "06/08/2024"],
  },
  {
    id: 7,
    url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-1_1716798361490.jpg",
    banner:
      "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
    title: "Mèo béo siêu quậy 7",
    movieSchedule: ["06/06/2024", "07/06/2024", "06/08/2024"],
    slug: "meo-beo-sieu-quay-7",
  },
  {
    id: 8,
    url: "https://cdn.galaxycine.vn/media/2024/5/27/garfield-1_1716798361490.jpg",
    banner:
      "https://cdn.galaxycine.vn/media/2024/5/27/garfield-2_1716798365891.jpg",
    title: "Mèo béo siêu quậy 8",
    movieSchedule: ["06/06/2024", "07/06/2024", "08/06/2024"],

    slug: "meo-beo-sieu-quay-8",
  },
];
export const promotionalNew = [
  {
    id: 1,
    title: "Cine Với Cạ Cứng - Tụ Tập Vui Quá Trời",
    url: "https://cdn.galaxycine.vn/media/2024/5/24/750_1716521545766.jpg",
  },
  {
    id: 2,
    title: "Cine Với Cạ Cứng - Tụ Tập Vui Quá ",
    url: "https://cdn.galaxycine.vn/media/2024/4/2/750_1712051414517.jpg",
  },
  {
    id: 3,
    title: "Cine Với Cạ Cứng - Tụ Tập Vui",
    url: "https://cdn.galaxycine.vn/media/2024/4/15/galaxy-da-co-1800x1200_1713168778020.jpg",
  },
  {
    id: 4,
    title: "Cine Với Cạ Cứng - Tụ Tập ",
    url: "https://cdn.galaxycine.vn/media/2023/5/23/quy-dinh-do-tuoi-digital-1350x900_1684835377244.jpg",
  },
  {
    id: 5,
    title:
      "Cine Với Cạ Cứng - Tụ Tập Vui Quá  Trời Trời Trời Trời Trời Trời Trời Trời Trời",
    url: "https://cdn.galaxycine.vn/media/2024/3/21/galaxy-studio-va-samsung-k-ket-hop-tac-chien-luoc--tai-dinh-nghia-su-ket-hop-giua-dien-anh--cong-nghe-6_1711006015662.jpg",
  },
];
export const Room = [
  {
    data: {
      maxRow: 9,
      maxColumn: 9,
      rows: [
        {
          name: "P",
          index: 0,
          seats: [
            {
              id: "1",
              area: 2,
              column: 0,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 0,
                },
                {
                  area: 2,
                  row: 0,
                  column: 1,
                },
              ],
            },
            {
              id: "2",
              area: 2,
              column: 1,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 0,
                },
                {
                  area: 2,
                  row: 0,
                  column: 1,
                },
              ],
            },
            {
              id: "3",
              area: 2,
              column: 2,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 2,
                },
                {
                  area: 2,
                  row: 0,
                  column: 3,
                },
              ],
            },
            {
              id: "4",
              area: 2,
              column: 3,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 2,
                },
                {
                  area: 2,
                  row: 0,
                  column: 3,
                },
              ],
            },
            {
              id: "5",
              area: 2,
              column: 4,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 4,
                },
                {
                  area: 2,
                  row: 0,
                  column: 5,
                },
              ],
            },
            {
              id: "6",
              area: 2,
              column: 5,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 4,
                },
                {
                  area: 2,
                  row: 0,
                  column: 5,
                },
              ],
            },
            {
              id: "7",
              area: 2,
              column: 6,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 6,
                },
                {
                  area: 2,
                  row: 0,
                  column: 7,
                },
              ],
            },
            {
              id: "8",
              area: 2,
              column: 7,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 6,
                },
                {
                  area: 2,
                  row: 0,
                  column: 7,
                },
              ],
            },
            {
              id: "9",
              area: 2,
              column: 8,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 8,
                },
                {
                  area: 2,
                  row: 0,
                  column: 9,
                },
              ],
            },
            {
              id: "10",
              area: 2,
              column: 9,
              row: 0,
              status: 0,
              ticketPrice: 190000,
              categoryCode: "0000000004",
              description: "COUPLE SEAT",
              type: 2,
              seatsInGroup: [
                {
                  area: 2,
                  row: 0,
                  column: 8,
                },
                {
                  area: 2,
                  row: 0,
                  column: 9,
                },
              ],
            },
          ],
        },
        {
          name: "I",
          index: 0,
          seats: [
            {
              id: "1",
              area: 1,
              column: 0,
              row: 0,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "2",
              area: 1,
              column: 1,
              row: 0,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "3",
              area: 1,
              column: 2,
              row: 0,
              status: 1,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "4",
              area: 1,
              column: 3,
              row: 0,
              status: 1,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "5",
              area: 1,
              column: 4,
              row: 0,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "6",
              area: 1,
              column: 5,
              row: 0,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "7",
              area: 1,
              column: 6,
              row: 0,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "8",
              area: 1,
              column: 7,
              row: 0,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
          ],
        },
        {
          name: "H",
          index: 1,
          seats: [
            {
              id: "1",
              area: 1,
              column: 0,
              row: 1,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "2",
              area: 1,
              column: 1,
              row: 1,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "3",
              area: 1,
              column: 2,
              row: 1,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "4",
              area: 1,
              column: 3,
              row: 1,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "5",
              area: 1,
              column: 4,
              row: 1,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "6",
              area: 1,
              column: 5,
              row: 1,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "7",
              area: 1,
              column: 6,
              row: 1,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "8",
              area: 1,
              column: 7,
              row: 1,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
          ],
        },
        {
          name: "G",
          index: 2,
          seats: [
            {
              id: "1",
              area: 1,
              column: 0,
              row: 2,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "2",
              area: 1,
              column: 1,
              row: 2,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "3",
              area: 1,
              column: 2,
              row: 2,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "4",
              area: 1,
              column: 3,
              row: 2,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "5",
              area: 1,
              column: 4,
              row: 2,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "6",
              area: 1,
              column: 5,
              row: 2,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "7",
              area: 1,
              column: 6,
              row: 2,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "8",
              area: 1,
              column: 7,
              row: 2,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
          ],
        },
        {
          name: "F",
          index: 3,
          seats: [
            {
              id: "1",
              area: 1,
              column: 0,
              row: 3,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "2",
              area: 1,
              column: 1,
              row: 3,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "3",
              area: 1,
              column: 2,
              row: 3,
              status: 1,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "4",
              area: 1,
              column: 3,
              row: 3,
              status: 1,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "5",
              area: 1,
              column: 4,
              row: 3,
              status: 1,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "6",
              area: 1,
              column: 5,
              row: 3,
              status: 1,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "7",
              area: 1,
              column: 6,
              row: 3,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "8",
              area: 1,
              column: 7,
              row: 3,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
          ],
        },
        {
          name: "E",
          index: 4,
          seats: [
            {
              id: "1",
              area: 1,
              column: 0,
              row: 4,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "2",
              area: 1,
              column: 1,
              row: 4,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "3",
              area: 1,
              column: 2,
              row: 4,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "4",
              area: 1,
              column: 3,
              row: 4,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "5",
              area: 1,
              column: 4,
              row: 4,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "6",
              area: 1,
              column: 5,
              row: 4,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "7",
              area: 1,
              column: 6,
              row: 4,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "8",
              area: 1,
              column: 7,
              row: 4,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "9",
              area: 1,
              column: 8,
              row: 4,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
          ],
        },
        {
          name: "D",
          index: 5,
          seats: [
            {
              id: "1",
              area: 1,
              column: 0,
              row: 5,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "2",
              area: 1,
              column: 1,
              row: 5,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "3",
              area: 1,
              column: 2,
              row: 5,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "4",
              area: 1,
              column: 3,
              row: 5,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "5",
              area: 1,
              column: 4,
              row: 5,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "6",
              area: 1,
              column: 5,
              row: 5,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "7",
              area: 1,
              column: 6,
              row: 5,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "8",
              area: 1,
              column: 7,
              row: 5,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "9",
              area: 1,
              column: 8,
              row: 5,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
          ],
        },
        {
          name: "C",
          index: 6,
          seats: [
            {
              id: "1",
              area: 1,
              column: 0,
              row: 6,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "2",
              area: 1,
              column: 1,
              row: 6,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "3",
              area: 1,
              column: 2,
              row: 6,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "4",
              area: 1,
              column: 3,
              row: 6,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "5",
              area: 1,
              column: 4,
              row: 6,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "6",
              area: 1,
              column: 5,
              row: 6,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "7",
              area: 1,
              column: 6,
              row: 6,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "8",
              area: 1,
              column: 7,
              row: 6,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "9",
              area: 1,
              column: 8,
              row: 6,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
          ],
        },
        {
          name: "B",
          index: 7,
          seats: [
            {
              id: "1",
              area: 1,
              column: 0,
              row: 7,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "2",
              area: 1,
              column: 1,
              row: 7,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "3",
              area: 1,
              column: 2,
              row: 7,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "4",
              area: 1,
              column: 3,
              row: 7,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "5",
              area: 1,
              column: 4,
              row: 7,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "6",
              area: 1,
              column: 5,
              row: 7,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "7",
              area: 1,
              column: 6,
              row: 7,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "8",
              area: 1,
              column: 7,
              row: 7,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "9",
              area: 1,
              column: 8,
              row: 7,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
          ],
        },
        {
          name: "A",
          index: 8,
          seats: [
            {
              id: "1",
              area: 1,
              column: 0,
              row: 8,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "2",
              area: 1,
              column: 1,
              row: 8,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "3",
              area: 1,
              column: 2,
              row: 8,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "4",
              area: 1,
              column: 3,
              row: 8,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "5",
              area: 1,
              column: 4,
              row: 8,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "6",
              area: 1,
              column: 5,
              row: 8,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "7",
              area: 1,
              column: 6,
              row: 8,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "8",
              area: 1,
              column: 7,
              row: 8,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
            {
              id: "9",
              area: 1,
              column: 8,
              row: 8,
              status: 0,
              ticketPrice: 85000,
              categoryCode: "0000000002",
              description: "Standard",
              type: 1,
              seatsInGroup: [],
            },
          ],
        },
      ],
      packages: [
        {
          ticketTypeCode: "1031",
          title: "GalaXummer",
          content: "HẠ NÓNG NỰC, RỰC SẮC SEA",
          note: "Khoan dừng khoảng chừng là 2 giây.Tiết kiệm đến 30% khi mua gói ưu đãi này",
          name: "GOI DI BAR XUMMER KVA",
          image:
            "https://cdn.galaxycine.vn/media/2024/5/14/packagecomboxummer-dibar-1563x1042_1715675080478.jpg",
          description:
            "Khoan dừng khoảng chừng là 2 giây \n\nTiết kiệm đến 30% khi mua gói ưu đãi này",
          price: 389000,
          quantity: 3,
        },
        {
          ticketTypeCode: "1030",
          title: "GalaXummer",
          content: "HẠ NÓNG NỰC, RỰC SẮC SEA",
          note: "Khoan dừng khoảng chừng là 2 giây.Tiết kiệm đến 30% khi mua gói ưu đãi này",
          name: "GOI CA CUNG XUMMER KVA",
          image:
            "https://cdn.galaxycine.vn/media/2024/5/14/packagecomboxummer-cacung-1563x1042_1715675043050.jpg",
          description:
            "Khoan dừng khoảng chừng là 2 giây \n\nTiết kiệm đến 30% khi mua gói ưu đãi này",
          price: 266000,
          quantity: 2,
        },
      ],
    },
  },
];
